### ISSUE TITLE
About swin_large_o365_finetune.pth

### ISSUE THREAD

**Issue by j0nghyukpark** [mingcv/DSIT#2]
Did you finetune the swin transformer to get 'swin_large_o365_finetune.pth'?
If so, can you provide settings for finetuning the swin transfomer? 

Thanks.

**Comment by mingcv** [comment]
We did not perform manual fine-tuning on the Swin Transformer. The file *swin_large_o365_finetune.pth* was sourced from the [[Detrex repository](https://github.com/IDEA-Research/detrex)]. You can access the same checkpoint via the [[Model Zoo](https://detrex.readthedocs.io/en/latest/tutorials/Model_Zoo.html)]: 
![image](https://github.com/user-attachments/assets/76bbd865-4589-4fce-8422-e025e6abd888)
